### ISSUE TITLE
[需求]当前生成token的方法过于繁琐

### ISSUE THREAD

**Issue by ghsssss** [AkenClub/ken-iMoutai-Script#10]
像城市，坐标，申购这些可以直接放环境变量中
版本号可以默认生成，

建议在登录接口输入手机号和验证码后然后一键生成token，然后再复制到环境变量中

**Comment by AkenClub** [comment]
谢谢提出建议。

现在拼接成一个变量是为了尽量不干扰用户环境变量列表，不方便管理。

流程的确可以简化一些，第一二步应该还是要分开生成的，因为要等用户输入验证码后再运行获取 Token。但是可以记录第一步的手机号码那些数据临时记录到环境变量，在第二部读取这些临时环境变量，等生成 Token 后自动拼接生成 KEN_IMAOTAI_ENV 并写入到环境变量，最后删除临时环境变量就行。

这样就只用在第一步填写：手机号码、省份、城市，第二部填写：验证码、自己选择的坐标、店铺 ID、申购ID列表，完成后就能正常预约了。

这样其实只是和第三步合并到第一步，然后增加一些环境变量的写入和删除，不用手动创建环境变量而已，也没能简化多少。

**Comment by ghsssss** [comment]
多用户的旅行可能会出现
🚫 旅行失败: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
建议加入sleep

**Comment by AkenClub** [comment]
> 多用户的旅行可能会出现 🚫 旅行失败: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) 建议加入sleep

我现在两个用户没有出现这情况。请问你是几个用户？出现这个情况是百分百复现吗？具体日志方便贴一下？

**Comment by ghsssss** [comment]
我也两个，就出现了一次，目前为止

**Comment by AkenClub** [comment]
> 我也两个，就出现了一次，目前为止

那先不加延迟了，其他接口都是没有加延迟了，运行这么久我也没出现过，你后续如果还出现的话可以先自己加延迟看看有没有改善
