### ISSUE TITLE
能不能增加一个web前端功能

### ISSUE THREAD

**Issue by 1552867145** [AkenClub/ken-iMoutai-Script#11]
如题所示 增加一个web前端功能

**Comment by AkenClub** [comment]
这个前端页面要做什么？另外脚本需要依赖青龙去定时触发执行任务，单做个前端页面是想要作甚？

**Comment by 1552867145** [comment]
> 这个前端页面要做什么？另外，脚本需要依赖青龙去定时触发执行任务，单做前端页面是想要做甚？

像网页版那样 方便别的朋友添加账号

**Comment by AkenClub** [comment]
> > 这个前端页面要做什么？另外，脚本需要依赖青龙去定时触发执行任务，单做前端页面是想要做甚？
> 
> 像网页版那样 方便别的朋友添加账号

可以看看这个项目，https://github.com/oddfar/campus-imaotai。本项目暂时无法提供前端页面，不好意思
