### ISSUE TITLE
运行4时提示没有Crypto模块

### ISSUE THREAD

**Issue by zy889** [AkenClub/ken-iMoutai-Script#12]
Traceback (most recent call last):
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 51, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by AkenClub** [comment]
缺少什么就安装什么依赖就行。参考常见问题。

缺少依赖，ModuleNotFoundError: No module named 'Crypto'？

解决：单独安装 pycryptodome 依赖

docker exec -it 青龙容器名 /bin/bash
在容器内使用 pip 安装 pycryptodome：

pip install pycryptodome

**Comment by zy889** [comment]
我刚看到下面有方案，感谢！
