### ISSUE TITLE
怀疑是python版本问题，4_预约申购 运行报错

### ISSUE THREAD

**Issue by boyiz** [AkenClub/ken-iMoutai-Script#13]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 648, in <module>
    start(user)
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 454, in start
    shop_id = get_shop_id_by_mode(user["LAT"], user["LNG"],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 583, in get_shop_id_by_mode
    shops_by_product_id = get_shop_by_product_id(province_name, product_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 532, in get_shop_by_product_id
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

青龙版本：v2.17.12

**Comment by AkenClub** [comment]
应该是解析接口返回的json数据出了问题，你能看看能不能加打印语句，然后把日志发一下？如果res很长的话，你提供一下api_url就好。最好有res，我怕链接过期无法访问
![image](https://github.com/user-attachments/assets/c6f4c1be-f39a-44a9-82b2-678bad7e08f4)
![image](https://github.com/user-attachments/assets/40128f11-69c8-41bb-90bb-6b15476bc597)

**Comment by AkenClub** [comment]
另外，你可以先试试文档里的 “环境变量示例”  - “指定店铺ID且不使用自动选择模式”，先不使用缺货自动模式

**Comment by boyiz** [comment]
> 应该是解析接口返回的json数据出了问题，你能看看能不能加打印语句，然后把日志发一下？如果res很长的话，你提供一下api_url就好。最好有res，我怕链接过期无法访问 ![image](https://private-user-images.githubusercontent.com/52781316/383382417-c6f4c1be-f39a-44a9-82b2-678bad7e08f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTk3MjUsIm5iZiI6MTczMDg1OTQyNSwicGF0aCI6Ii81Mjc4MTMxNi8zODMzODI0MTctYzZmNGMxYmUtZjM5YS00NGE5LTgyYjItNjc4YmFkN2UwOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAyMTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNjQ2ZDA0NmQwYTI1ZmMyYjNlMzQ0YmRhZjc0MDBhMGIwYTRhM2IxNjEyYTNmZTExZTk0MTRhNDY1ODEzZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ayORbCCx9cRvTlnGRmjXJk3TBY9x5uvOXQT1P8qSZxw) ![image](https://private-user-images.githubusercontent.com/52781316/383383123-40128f11-69c8-41bb-90bb-6b15476bc597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTk3MjUsIm5iZiI6MTczMDg1OTQyNSwicGF0aCI6Ii81Mjc4MTMxNi8zODMzODMxMjMtNDAxMjhmMTEtNjljOC00MWJiLTkwYmItNmIxNTQ3NmJjNTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAyMTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZTAwYzUzZDg5MWQ5ODJlNjM4NjEyMzc3ZjFkOWZkZjJhYmUyZGNjNDE2YTRlMDc3ZjNjMWU4YThmMWI5YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.47Up7pu8YO5I-tO0KMxtP5gCqPvCJgpJsvXLBsD2F1s)

抱歉，我的锅，通过你的提醒我进行调试，发现是商品ID写错了导致返回结果404，修改后正常，抱歉抱歉，已closed
