### ISSUE TITLE
多账号推送

### ISSUE THREAD

**Issue by 1552867145** [AkenClub/ken-iMoutai-Script#14]
有没有什么办法可以每个账号推送给不同的人

**Comment by AkenClub** [comment]
可以问问ai帮你实现一下就好，比如要推送到企业微信，在每个用户的环境变量值后面加多他的机器人id，之后每个用户预约完加多个方法推送给该用户就好。

**Comment by 1552867145** [comment]
运行4_reserve_product.py时店铺ID无法获取，2024-11-26 19:36:05,769 - INFO - 店铺ID - SHOP_ID

**Comment by 1552867145** [comment]
> 可以问问ai帮你实现就好了，比如要推送到企业微信，在每个用户的环境变量值后面加多他的机器人id，之后每个用户预约完加多个方法推送给该用户就好了。

用了ai的办法失败了 表哥能不能讲一下具体怎么操作呀

**Comment by AkenClub** [comment]
> > 可以问问ai帮你实现就好了，比如要推送到企业微信，在每个用户的环境变量值后面加多他的机器人id，之后每个用户预约完加多个方法推送给该用户就好了。
> 
> 用了ai的办法失败了 表哥能不能讲一下具体怎么操作呀

你是要推送什么渠道的？TGbot？企微机器人？

**Comment by 1552867145** [comment]
> > > 可以问问ai帮你实现就好了，比如要推送到企业微信，在每个用户的环境变量值后面加多他的机器人id，之后每个用户预约完加多个方法推送给该用户就好了。
> > 
> > 
> > 用了ai的办法失败了 表哥能不能讲一下具体怎么操作呀
> 
> 你是要推送什么渠道的？TGbot？企微机器人？

方糖

**Comment by AkenClub** [comment]
> > > > 可以问问ai帮你实现就好了，比如要推送到企业微信，在每个用户的环境变量值后面加多他的机器人id，之后每个用户预约完加多个方法推送给该用户就好了。
> > > 
> > > 
> > > 用了ai的办法失败了 表哥能不能讲一下具体怎么操作呀
> > 
> > 
> > 你是要推送什么渠道的？TGbot？企微机器人？
> 
> 方糖

https://github.com/easychen/serverchan-demo/blob/master/python/send.py
是指server酱的话可以看看上面示例，先跑通发送消息，之后在脚本你需要发通知的地方插入代码就好

**Comment by AkenClub** [comment]
> > 可以问问ai帮你实现就好了，比如要推送到企业微信，在每个用户的环境变量值后面加多他的机器人id，之后每个用户预约完加多个方法推送给该用户就好了。
> 
> 用了ai的办法失败了 表哥能不能讲一下具体怎么操作呀

你把方糖的调用方式和整篇脚本和环境变量一起喂给ai，应该是大概率能给你写出答案来的

**Comment by 1552867145** [comment]
> > > > > 可以问问ai帮你实现就好了，比如要推送到企业微信，在每个用户的环境变量值后面加多他的机器人id，之后每个用户预约完加多个方法推送给该用户就好了。
> > > > 
> > > > 
> > > > 用了ai的办法失败了 表哥能不能讲一下具体怎么操作呀
> > > 
> > > 
> > > 你是要推送什么渠道的？TGbot？企微机器人？
> > 
> > 
> > 方糖
> 
> https://github.com/easychen/serverchan-demo/blob/master/python/send.py 是指server酱的话可以看看上面示例，先跑通发送消息，之后在脚本你需要发通知的地方插入代码就好

谢谢大佬解答 期待大佬的查询中签功能

**Comment by AkenClub** [comment]
> > > > > > 可以问问ai帮你实现就好了，比如要推送到企业微信，在每个用户的环境变量值后面加多他的机器人id，之后每个用户预约完加多个方法推送给该用户就好了。
> > > > > 
> > > > > 
> > > > > 用了ai的办法失败了 表哥能不能讲一下具体怎么操作呀
> > > > 
> > > > 
> > > > 你是要推送什么渠道的？TGbot？企微机器人？
> > > 
> > > 
> > > 方糖
> > 
> > 
> > https://github.com/easychen/serverchan-demo/blob/master/python/send.py 是指server酱的话可以看看上面示例，先跑通发送消息，之后在脚本你需要发通知的地方插入代码就好
> 
> 谢谢大佬解答 期待大佬的查询中签功能

不客气，查询中签功能一直没时间做，不过如果你中签的话会有短信通知的😁
