### ISSUE TITLE
运行1以后，拿不到DEVICE_ID呀

### ISSUE THREAD

**Issue by zhzh213** [AkenClub/ken-iMoutai-Script#15]
返回值如下：
 if send_code(PHONE_NUMBER, device_id, mt_version):
            logging.info(f"{PHONE_NUMBER}：验证码发送成功，请注意查收!")

            logging.info("****************************")
            logging.info("记录以下信息用于后续登录：")
            logging.info(f"设备ID - DEVICE_ID：{device_id}")
            logging.info(f"版本号 - MT_VERSION：{mt_version}")
    except Exception as e:
        logging.error(e)

## 开始执行... 2024-12-11 08:42:45

2024-12-11 08:42:46,770 - INFO - 「发送验证码返回」：{"code": 2000}

2024-12-11 08:42:46,772 - INFO - 135*****55（码掉）：验证码发送成功，请注意查收!

2024-12-11 08:42:46,773 - INFO - 版本号 - MT_VERSION：1.7.5

**Comment by AkenClub** [comment]
![image](https://github.com/user-attachments/assets/e81376d7-35d3-44dc-87a4-27e3c8f8f1d8)
刚尝试了一下，可以输出版本号的，你进调试看看是怎样输出的？

**Comment by zhzh213** [comment]
搞定了，青龙的python3没request库
