### ISSUE TITLE
获取耐力值奖励失败，是需要九点以后才会正常运行么

### ISSUE THREAD

**Issue by 778154145** [AkenClub/ken-iMoutai-Script#2]
所有商品预约完成, 3 秒后获取耐力值奖励
开始获取耐力值奖励
获取耐力值奖励失败: [ianus-token-auth] invalid signature
查询 & 领取累计申购的小茅运
查询 & 领取累计申购的小茅运失败: 查询累计申购奖励失败: [ianus-token-auth] invalid signature
查询 & 领取 7 日连续申购领取小茅运
7 日连续申购领取小茅运奖励异常: 查询失败: [ianus-token-auth] invalid signature

**Comment by 778154145** [comment]
运行时间是8点30分，只是想试试是否正常运行

**Comment by AkenClub** [comment]
[ianus-token-auth] invalid signature
这个应该是token过期或者你 token 填错，可以重新走一下第一二步。
另外，是9点后才开始的，可以看看app上的预约规则

**Comment by 778154145** [comment]
好的，谢谢

**Comment by AkenClub** [comment]
你好，你这个问题可以看看下面复现后的解决方法。

运行脚本返回 [ianus-token-auth] bad token; invalid signature 错误？

解决： 检查环境变量是否设置正确。出现该错误一般是因为 值 填了 KEN_IMAOTAI_ENV="13312345678$..$.."，脚本解析环境变量时 COOKIE 部分多了一个 "，导致报错。去除KEN_IMAOTAI_ENV=""即可，值 只填写真实获取到的数值就行。

注意：编辑变量弹窗里，名称的输入框内填固定值：KEN_IMAOTAI_ENV，值的输入框填真实信息：13312345678$..$..。下方示例中只展示值部分。
