### ISSUE TITLE
请问运行错误，怎么解决呢？

### ISSUE THREAD

**Issue by cktea** [AkenClub/ken-iMoutai-Script#3]
## 开始执行... 2024-09-18 09:10:07

Traceback (most recent call last):
  File "/ql/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 38, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

## 执行结束... 2024-09-18 09:10:17 耗时 10 秒

**Comment by AkenClub** [comment]
https://github.com/FlechazoPh/QLDependency
可以用一下这个一键安装依赖的库，或者搜索引擎查一下报错的问题，单独安装模块依赖

**Comment by AkenClub** [comment]
`docker exec -it 青龙容器名 /bin/bash`

在容器内使用 pip 安装 pycryptodome：

`pip install pycryptodome`

**Comment by AkenClub** [comment]
也已经更新到“常见问题”里面了
