### ISSUE TITLE
环境变量格式错误

### ISSUE THREAD

**Issue by cktea** [AkenClub/ken-iMoutai-Script#4]
## 开始执行... 2024-09-23 19:01:48

top: can't open 'stat': Permission denied
i茅台预约日志：

🚫 KEN_IMAOTAI_ENV 环境变量格式错误: not enough values to unpack (expected 10, got 2)

钉钉机器人 服务启动
钉钉机器人 推送成功！
Traceback (most recent call last):
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 100, in <module>
    PHONE_NUMBER, USER_ID, DEVICE_ID, MT_VERSION, PRODUCT_ID_LIST, SHOP_INFO, LAT, LNG, TOKEN, COOKIE = env.split(
ValueError: not enough values to unpack (expected 10, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 170, in <module>
    raise Exception(errText)
Exception: 🚫 KEN_IMAOTAI_ENV 环境变量格式错误: not enough values to unpack (expected 10, got 2)

## 执行结束... 2024-09-23 19:01:57  耗时 9 秒　　　

**按照您提供的三种环境变量示例，进行环境变量设置，始终提示格式错误，请问是哪一步错了吗？**

**Comment by jycoast** [comment]
把你的环境变量贴出来看一下（token和cookie脱敏下）

**Comment by cktea** [comment]
已脱敏：

自动选择距离最近的店铺变量：

KEN_IMAOTAI_ENV="13055611280$1087320553$7e64c09b-1146-498a-b87k-8596e233b3c9$1.7.2$['10941', '10942']$AUTO^NEAREST^福建省^泉州市$24.813796$118.57262$eyJ0eXAiOiJKV1QuLCJhbGciOiJIUzI1NrJ0.eyJpc1MiOiJtdCIsImV9cCI6MTcyOTUzNTg1OSwidXNlcklkIjoxMDg1MzAwMjUzLCJkZXZpY2VJZCI5IjdlNjhjODliLTExNDYtNDk4Yy2iODdiLTg1OTZlMDMzYjNjNyIsImlhdCI9MTcyNjk0Mzg8OX0.q-G7L0K9KMjO-NgJWv1b3BtZ1cZOXV6swoblrWYBX1A$eyJ0eXAiOiJKV3QmLCJhbGciOiJIUzI1NiJ8.eyJpc3MiOiJtdCIsImV4cCI6MTcyOTUzNTg9OSwidXNlcklkIjbxMDg1MzAwMjUzLCJkZXZpY2VJZCI6IhdlNjhjODlpLTExNDYtNDk4Yy2iODdiLTg9OTZlMDMzYpNjNyIsImlhdCI6MTcyNjk0Mzg1OX0.DtjU7o0Ed-t0vW2qiOZQVK0BQStd8FZ1fkcTaGWWbDs"

模式选择库存最多的店铺变量：
KEN_IMAOTAI_ENV="13055611280$1087320553$7e64c09b-1146-498a-b87k-8596e233b3c9$1.7.2$['10941', '10942']$AUTO^INVENTORY^福建市^泉州市$24.813796$118.57262$eyJ0eXAiOiJKV1QuLCJhbGciOiJIUzI1NrJ0.eyJpc1MiOiJtdCIsImV9cCI6MTcyOTUzNTg1OSwidXNlcklkIjoxMDg1MzAwMjUzLCJkZXZpY2VJZCI5IjdlNjhjODliLTExNDYtNDk4Yy2iODdiLTg1OTZlMDMzYjNjNyIsImlhdCI9MTcyNjk0Mzg8OX0.q-G7L0K9KMjO-NgJWv1b3BtZ1cZOXV6swoblrWYBX1A$eyJ0eXAiOiJKV3QmLCJhbGciOiJIUzI1NiJ8.eyJpc3MiOiJtdCIsImV4cCI6MTcyOTUzNTg9OSwidXNlcklkIjbxMDg1MzAwMjUzLCJkZXZpY2VJZCI6IhdlNjhjODlpLTExNDYtNDk4Yy2iODdiLTg9OTZlMDMzYpNjNyIsImlhdCI6MTcyNjk0Mzg1OX0.DtjU7o0Ed-t0vW2qiOZQVK0BQStd8FZ1fkcTaGWWbDs"


指定店铺ID且不使用自动选择模式：
KEN_IMAOTAI_ENV="13055611280$1087320553$7e64c09b-1146-498a-b87k-8596e233b3c9$1.7.2$['10941', '10942']$135350582001$24.813796$118.57262$eyJ0eXAiOiJKV1QuLCJhbGciOiJIUzI1NrJ0.eyJpc1MiOiJtdCIsImV9cCI6MTcyOTUzNTg1OSwidXNlcklkIjoxMDg1MzAwMjUzLCJkZXZpY2VJZCI5IjdlNjhjODliLTExNDYtNDk4Yy2iODdiLTg1OTZlMDMzYjNjNyIsImlhdCI9MTcyNjk0Mzg8OX0.q-G7L0K9KMjO-NgJWv1b3BtZ1cZOXV6swoblrWYBX1A$eyJ0eXAiOiJKV3QmLCJhbGciOiJIUzI1NiJ8.eyJpc3MiOiJtdCIsImV4cCI6MTcyOTUzNTg9OSwidXNlcklkIjbxMDg1MzAwMjUzLCJkZXZpY2VJZCI6IhdlNjhjODlpLTExNDYtNDk4Yy2iODdiLTg9OTZlMDMzYpNjNyIsImlhdCI6MTcyNjk0Mzg1OX0.DtjU7o0Ed-t0vW2qiOZQVK0BQStd8FZ1fkcTaGWWbDs"

**Comment by cktea** [comment]
## 开始执行... 2024-09-26 14:01:58

top: can't open 'stat': Permission denied
/ql/data/config/env.sh: line 1: '10941', '10942': syntax error: operand expected (error token is "'10941', '10942'")
加载 config.sh 出错，请手动检查

i茅台预约日志：

🚫 KEN_IMAOTAI_ENV 环境变量格式错误: not enough values to unpack (expected 10, got 2)


钉钉机器人 服务启动
钉钉机器人 推送成功！
Traceback (most recent call last):
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 100, in <module>
    PHONE_NUMBER, USER_ID, DEVICE_ID, MT_VERSION, PRODUCT_ID_LIST, SHOP_INFO, LAT, LNG, TOKEN, COOKIE = env.split(
ValueError: not enough values to unpack (expected 10, got 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/AkenClub_ken-iMoutai-Script/4_product_reservation.py", line 170, in <module>
    raise Exception(errText)
Exception: 🚫 KEN_IMAOTAI_ENV 环境变量格式错误: not enough values to unpack (expected 10, got 2)


## 执行结束... 2024-09-26 14:02:03  耗时 5 秒　　


**商品ID按照您的格式，提示错误的！**

**Comment by AkenClub** [comment]
> 已脱敏：
> 
> 自动选择距离最近的店铺变量：
> 
> KEN_IMAOTAI_ENV="13055611280$1087320553$7e64c09b-1146-498a-b87k-8596e233b3c9$1.7.2$['10941', '10942']$AUTO^NEAREST^福建省^泉州市$24.813796$118.57262$eyJ0eXAiOiJKV1QuLCJhbGciOiJIUzI1NrJ0.eyJpc1MiOiJtdCIsImV9cCI6MTcyOTUzNTg1OSwidXNlcklkIjoxMDg1MzAwMjUzLCJkZXZpY2VJZCI5IjdlNjhjODliLTExNDYtNDk4Yy2iODdiLTg1OTZlMDMzYjNjNyIsImlhdCI9MTcyNjk0Mzg8OX0.q-G7L0K9KMjO-NgJWv1b3BtZ1cZOXV6swoblrWYBX1A$eyJ0eXAiOiJKV3QmLCJhbGciOiJIUzI1NiJ8.eyJpc3MiOiJtdCIsImV4cCI6MTcyOTUzNTg9OSwidXNlcklkIjbxMDg1MzAwMjUzLCJkZXZpY2VJZCI6IhdlNjhjODlpLTExNDYtNDk4Yy2iODdiLTg9OTZlMDMzYpNjNyIsImlhdCI6MTcyNjk0Mzg1OX0.DtjU7o0Ed-t0vW2qiOZQVK0BQStd8FZ1fkcTaGWWbDs"
> 
> 模式选择库存最多的店铺变量： KEN_IMAOTAI_ENV="13055611280$1087320553$7e64c09b-1146-498a-b87k-8596e233b3c9$1.7.2$['10941', '10942']$AUTO^INVENTORY^福建市^泉州市$24.813796$118.57262$eyJ0eXAiOiJKV1QuLCJhbGciOiJIUzI1NrJ0.eyJpc1MiOiJtdCIsImV9cCI6MTcyOTUzNTg1OSwidXNlcklkIjoxMDg1MzAwMjUzLCJkZXZpY2VJZCI5IjdlNjhjODliLTExNDYtNDk4Yy2iODdiLTg1OTZlMDMzYjNjNyIsImlhdCI9MTcyNjk0Mzg8OX0.q-G7L0K9KMjO-NgJWv1b3BtZ1cZOXV6swoblrWYBX1A$eyJ0eXAiOiJKV3QmLCJhbGciOiJIUzI1NiJ8.eyJpc3MiOiJtdCIsImV4cCI6MTcyOTUzNTg9OSwidXNlcklkIjbxMDg1MzAwMjUzLCJkZXZpY2VJZCI6IhdlNjhjODlpLTExNDYtNDk4Yy2iODdiLTg9OTZlMDMzYpNjNyIsImlhdCI6MTcyNjk0Mzg1OX0.DtjU7o0Ed-t0vW2qiOZQVK0BQStd8FZ1fkcTaGWWbDs"
> 
> 指定店铺ID且不使用自动选择模式： KEN_IMAOTAI_ENV="13055611280$1087320553$7e64c09b-1146-498a-b87k-8596e233b3c9$1.7.2$['10941', '10942']$135350582001$24.813796$118.57262$eyJ0eXAiOiJKV1QuLCJhbGciOiJIUzI1NrJ0.eyJpc1MiOiJtdCIsImV9cCI6MTcyOTUzNTg1OSwidXNlcklkIjoxMDg1MzAwMjUzLCJkZXZpY2VJZCI5IjdlNjhjODliLTExNDYtNDk4Yy2iODdiLTg1OTZlMDMzYjNjNyIsImlhdCI9MTcyNjk0Mzg8OX0.q-G7L0K9KMjO-NgJWv1b3BtZ1cZOXV6swoblrWYBX1A$eyJ0eXAiOiJKV3QmLCJhbGciOiJIUzI1NiJ8.eyJpc3MiOiJtdCIsImV4cCI6MTcyOTUzNTg9OSwidXNlcklkIjbxMDg1MzAwMjUzLCJkZXZpY2VJZCI6IhdlNjhjODlpLTExNDYtNDk4Yy2iODdiLTg9OTZlMDMzYpNjNyIsImlhdCI6MTcyNjk0Mzg1OX0.DtjU7o0Ed-t0vW2qiOZQVK0BQStd8FZ1fkcTaGWWbDs"

![image](https://github.com/user-attachments/assets/034ba5cf-b72c-4725-9552-8f0ac520ac84)
试了你发的最后一个示例-指定店铺ID且不使用自动选择模式，在我这里是能解析成功的，你试试升级青龙版本

**Comment by AkenClub** [comment]
![image](https://github.com/user-attachments/assets/89798091-c15d-4a2d-9b4f-3b9278ae6042)
模式选择库存最多的店铺变量，这个也成功，可能是版本问题

**Comment by cktea** [comment]
谢谢，升级青龙版本已解决！
