### ISSUE TITLE
检查真实 API 连通性失败: {'[ianus-token-auth] bad token; invalid signature'}

### ISSUE THREAD

**Issue by xiaonaiquan** [AkenClub/ken-iMoutai-Script#5]
在验证token的pyl里面输出：检查真实 API 连通性失败: {'[ianus-token-auth] bad token; invalid signature'}

**Comment by AkenClub** [comment]
> 在验证token的pyl里面输出：检查真实 API 连通性失败: {'[ianus-token-auth] bad token; invalid signature'}

完整的日志发一下？另外你执行4或者5步的脚本应该也会报这个错？token有没有填错？填完整？

**Comment by xiaonaiquan** [comment]
> > 在验证token的pyl里面输出：检查真实 API 连通性失败: {'[ianus-token-auth] bad token; invalid signature'}
> 
> 完整的日志发一下？另外你执行4或者5步的脚本应该也会报这个错？token有没有填错？填完整？

![42ce7058db300cf14cafbe627591f14](https://github.com/user-attachments/assets/bca3f444-6039-44bc-8138-efe11326334b)

**Comment by xiaonaiquan** [comment]
我能保证token是没有问题的，就是第二步复制的

**Comment by AkenClub** [comment]
> 我能保证token是没有问题的，就是第二步复制的

你执行第4 5步任意一个能调用成功吗？

**Comment by xiaonaiquan** [comment]
> > 我能保证token是没有问题的，就是第二步复制的
> 
> 你执行第4 5步任意一个能调用成功吗？

![image](https://github.com/user-attachments/assets/fff392af-f376-4f87-9766-110a6c8720f8)
第五步的报错

**Comment by AkenClub** [comment]
> > > 我能保证token是没有问题的，就是第二步复制的
> > 
> > 
> > 你执行第4 5步任意一个能调用成功吗？
> 
> ![image](https://private-user-images.githubusercontent.com/16412671/371081136-fff392af-f376-4f87-9766-110a6c8720f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQzMDcsIm5iZiI6MTcyNzM0NDAwNywicGF0aCI6Ii8xNjQxMjY3MS8zNzEwODExMzYtZmZmMzkyYWYtZjM3Ni00Zjg3LTk3NjYtMTEwYTZjODcyMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNzUyZDNmZTcyODk3NTlmYWVmMTRhZTNhMGZiODZhMmFjZjk3YWUxNTE1YTEwN2FiMGI1MzM0ZWY3MTQ4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bdIJHqRjaEx56sB_Q3GBgLBXtOF-EZNg5Vno_QUBRTo) 第五步的报错

重新执行一次1 2步拿新的数据吧，包括uuid等等信息，token生成时候会用到那些信息，估计也会校验

**Comment by xiaonaiquan** [comment]
> > > > 我能保证token是没有问题的，就是第二步复制的
> > > 
> > > 
> > > 你执行第4 5步任意一个能调用成功吗？
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/16412671/371081136-fff392af-f376-4f87-9766-110a6c8720f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQzMDcsIm5iZiI6MTcyNzM0NDAwNywicGF0aCI6Ii8xNjQxMjY3MS8zNzEwODExMzYtZmZmMzkyYWYtZjM3Ni00Zjg3LTk3NjYtMTEwYTZjODcyMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNzUyZDNmZTcyODk3NTlmYWVmMTRhZTNhMGZiODZhMmFjZjk3YWUxNTE1YTEwN2FiMGI1MzM0ZWY3MTQ4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bdIJHqRjaEx56sB_Q3GBgLBXtOF-EZNg5Vno_QUBRTo) 第五步的报错
> 
> 重新执行一次1 2步拿新的数据吧，包括uuid等等信息，token生成时候会用到那些信息，估计也会校验

嗯 ，试过两次 ，我一会儿再试一下

**Comment by xiaonaiquan** [comment]
> > > > 我能保证token是没有问题的，就是第二步复制的
> > > 
> > > 
> > > 你执行第4 5步任意一个能调用成功吗？
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/16412671/371081136-fff392af-f376-4f87-9766-110a6c8720f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQzMDcsIm5iZiI6MTcyNzM0NDAwNywicGF0aCI6Ii8xNjQxMjY3MS8zNzEwODExMzYtZmZmMzkyYWYtZjM3Ni00Zjg3LTk3NjYtMTEwYTZjODcyMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNzUyZDNmZTcyODk3NTlmYWVmMTRhZTNhMGZiODZhMmFjZjk3YWUxNTE1YTEwN2FiMGI1MzM0ZWY3MTQ4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bdIJHqRjaEx56sB_Q3GBgLBXtOF-EZNg5Vno_QUBRTo) 第五步的报错
> 
> 重新执行一次1 2步拿新的数据吧，包括uuid等等信息，token生成时候会用到那些信息，估计也会校验

试了好几次了，还是一样的错误

**Comment by xiaonaiquan** [comment]
> > > > > > 我能保证token是没有问题的，就是第二步复制的
> > > > > 
> > > > > 
> > > > > 你执行第4 5步任意一个能调用成功吗？
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/16412671/371081136-fff392af-f376-4f87-9766-110a6c8720f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQzMDcsIm5iZiI6MTcyNzM0NDAwNywicGF0aCI6Ii8xNjQxMjY3MS8zNzEwODExMzYtZmZmMzkyYWYtZjM3Ni00Zjg3LTk3NjYtMTEwYTZjODcyMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNzUyZDNmZTcyODk3NTlmYWVmMTRhZTNhMGZiODZhMmFjZjk3YWUxNTE1YTEwN2FiMGI1MzM0ZWY3MTQ4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bdIJHqRjaEx56sB_Q3GBgLBXtOF-EZNg5Vno_QUBRTo) 第五步的报错
> > > 
> > > 
> > > 重新执行一次1 2步拿新的数据吧，包括uuid等等信息，token生成时候会用到那些信息，估计也会校验
> > 
> > 
> > 试了好几次了，还是一样的错误
> 
> 你可以试试把token cookie的值复制到下面网站解开jwt，然后看用户id什么的有没有对应上 https://jwt.io/

jwt解出来，没啥问题，device_id 和  user_id都对应的上

**Comment by xiaonaiquan** [comment]
![image](https://github.com/user-attachments/assets/c090837f-bd63-4878-8d4c-60085ded300c)

**Comment by AkenClub** [comment]
> ![image](https://private-user-images.githubusercontent.com/16412671/371405969-c090837f-bd63-4878-8d4c-60085ded300c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTYxMTIsIm5iZiI6MTcyNzQxNTgxMiwicGF0aCI6Ii8xNjQxMjY3MS8zNzE0MDU5NjktYzA5MDgzN2YtYmQ2My00ODc4LThkNGMtNjAwODVkZWQzMDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA1NDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4N2EzNzYzMDFkNjdiMTQyOWUzYTlmODAxMzYyYmJiYmNiNTQwNjZhMjZkZWYxOGYyNzRhY2YzNWRkNDI4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0ZMD_U4H93xWbBWMoYNuYS51skcsIRw9A-OfMKkXfrA)

看你这图的日志，预约是成功的了，就是后面领取接口报的错，那应该token没问题。我到今日都是正常运行，没有见其他人报这个问题，帮不了你。
或者试试升级一下青龙版本？重新拉库？之类的？

**Comment by xiaonaiquan** [comment]
> > ![image](https://private-user-images.githubusercontent.com/16412671/371405969-c090837f-bd63-4878-8d4c-60085ded300c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTYxMTIsIm5iZiI6MTcyNzQxNTgxMiwicGF0aCI6Ii8xNjQxMjY3MS8zNzE0MDU5NjktYzA5MDgzN2YtYmQ2My00ODc4LThkNGMtNjAwODVkZWQzMDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA1NDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4N2EzNzYzMDFkNjdiMTQyOWUzYTlmODAxMzYyYmJiYmNiNTQwNjZhMjZkZWYxOGYyNzRhY2YzNWRkNDI4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0ZMD_U4H93xWbBWMoYNuYS51skcsIRw9A-OfMKkXfrA)
> 
> 看你这图的日志，预约是成功的了，就是后面领取接口报的错，那应该token没问题。我到今日都是正常运行，没有见其他人报这个问题，帮不了你。 或者试试升级一下青龙版本？重新拉库？之类的？

没事儿 ，申购行，后面的先不管了，感谢大佬

**Comment by AkenClub** [comment]
你好，你这个问题可以看看下面复现后的解决方法。

运行脚本返回 [ianus-token-auth] bad token; invalid signature 错误？

解决： 检查环境变量是否设置正确。出现该错误一般是因为 值 填了 KEN_IMAOTAI_ENV="13312345678$..$.."，脚本解析环境变量时 COOKIE 部分多了一个 "，导致报错。去除KEN_IMAOTAI_ENV=""即可，值 只填写真实获取到的数值就行。

注意：编辑变量弹窗里，名称的输入框内填固定值：KEN_IMAOTAI_ENV，值的输入框填真实信息：13312345678$..$..。下方示例中只展示值部分。
