### ISSUE TITLE
检查异常: module 'jwt' has no attribute 'DecodeError'，请手动执行 4、5 脚本，检查 TOKEN、COOKIE 是否过期

### ISSUE THREAD

**Issue by Harveeeeyz** [AkenClub/ken-iMoutai-Script#7]
佬大，依赖没问题啊，是哪里出的问题，其他功能都不影响，就是查不了token有效期

**Comment by AkenClub** [comment]
你可以谷歌搜索一下原因先的。
我查了一下有说是不是同时装了jwt和和pyjwt？

**Comment by ghsssss** [comment]
# jwt卸载命令

pip uninstall jwt

# 保险起见，将PyJWT一同卸载

pip uninstall PyJWT

# 重新安装PyJWT

pip install PyJWT
